{% set name = "demesdraw" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fb773fa461fdb2cabeba4c1c78e765bacf8a93e9b4fcd6ed09e1a30062e1827

build:
  number: 1
  noarch: python
  entry_points:
    - demesdraw = demesdraw.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - demes >=0.2.1
    - matplotlib-base >=3.3.1
    - numpy
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - demesdraw
  commands:
    - pip check
    - demesdraw --version
    - demes ms -N0 1 -I 2 0 0 0.1 -es 1 1 0.99 -ej 1 3 2 -ej 100 2 1 | demesdraw tubes - /tmp/tubes.svg
    - demes ms -N0 100 -G 0.01 -eN 100 1 | demesdraw size_history - /tmp/size_history.svg
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/grahamgower/demesdraw
  summary: drawing tools for Demes demographic models
  license: ISC
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grahamgower
