{% set name = "demesdraw" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1880f00e7180a6ef4fb97f80ccbe0bb1f5e38752666a767eab3923065cb668a6

build:
  number: 0
  noarch: python
  entry_points:
    - demesdraw = demesdraw.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - cvxpy
    - demes >=0.2.1
    - matplotlib-base >=3.3.1
    - numpy
    - python >=3.6

test:
  imports:
    - demesdraw
  commands:
    - pip check
    - demesdraw --version
    - demes ms -N0 1 -I 2 0 0 0.1 -es 1 1 0.99 -ej 1 3 2 -ej 100 2 1 | demesdraw tubes - /tmp/tubes.svg
    - demes ms -N0 100 -G 0.01 -eN 100 1 | demesdraw size_history - /tmp/size_history.svg
  requires:
    - pip

about:
  home: https://github.com/grahamgower/demesdraw
  summary: drawing tools for Demes demographic models
  license: ISC
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grahamgower
