{% set name = "demesdraw" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a165e45b82da60adde737e80a6805819037e710e549fb2ea87ae97aed99ea240

build:
  number: 0
  noarch: python
  entry_points:
    - demesdraw = demesdraw.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-scm
  run:
    - demes >=0.1.2,<0.2
    - matplotlib-base >=3.3.1
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - demesdraw
  commands:
    - pip check
    - demesdraw --help
  requires:
    - pip

about:
  home: https://github.com/grahamgower/demesdraw
  summary: drawing tools for Demes demographic models
  license: ISC
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - grahamgower
